@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueResidentList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueResidentList
UniqueTagList -[hidden]down- UniqueResidentList

UniqueTagList -right-> "*" Tag
UniqueResidentList -right-> Resident

Resident -up-> "*" Tag

Resident *--> Name
Resident *--> Phone
Resident *--> Email
Resident *--> Address
@enduml
